export const imageArray = [
    [require('./assets/images/1.jpg'), 12],
    [require('./assets/images/2.jpg'), 8],
    [require('./assets/images/3.jpg'), 6],
    [require('./assets/images/4.jpg'), 29],
    [require('./assets/images/5.jpg'), 57],
    [require('./assets/images/6.jpg'), 5],
    [require('./assets/images/7.jpg'), 3],
    [require('./assets/images/8.jpg'), 15],
    [require('./assets/images/9.jpg'), 74],
    [require('./assets/images/10.jpg'), 2],
    [require('./assets/images/11.jpg'), 6],
    [require('./assets/images/12.jpg'), 97],
    [require('./assets/images/13.jpg'), 45],
    [require('./assets/images/14.jpg'), 5],
    [require('./assets/images/15.jpg'), 7],
    [require('./assets/images/16.jpg'), 16],
    [require('./assets/images/17.jpg'), 73],
    [require('./assets/images/18.jpg'), "nothing"],
    [require('./assets/images/19.jpg'), "nothing"],
    [require('./assets/images/20.jpg'), 26],
    [require('./assets/images/21.jpg'), 42],
    [require('./assets/images/22.jpg'), 35],
    [require('./assets/images/23.jpg'), 96],
    [require('./assets/images/24.jpg'), "2 lines"],
    [require('./assets/images/25.jpg'), "nothing"],
    [require('./assets/images/26.jpg'), "nothing"],
    [require('./assets/images/27.jpg'), "line"],
    [require('./assets/images/28.jpg'), "line"],
    [require('./assets/images/29.jpg'), "line"],
    [require('./assets/images/30.jpg'), "line"],
];
